/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiComponents.BloodRequestManagement;

import business.Bloodbank.directories.CommunityDirectory;
import business.Bloodbank.directories.CredentialsDirectory;
import business.Bloodbank.directories.HospitalDirectory;
import business.Bloodbank.resources.BloodGroupDetails;
import business.Bloodbank.resources.Community;
import business.Bloodbank.resources.Credentials;
import business.Bloodbank.resources.BBHospital;
import business.Bloodbank.resources.HospitalDetails;
import business.Bloodbank.resources.Person;
import business.Bloodbank.resources.PersonalDetails;
import business.Bloodbank.resources.Role;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class CommunityAdminPanel extends javax.swing.JPanel {

    private JTable table;

    /**
     * Creates new form CommunityAdminPanel
     */
    private ArrayList<BBHospital> hospitalResultSet;
    private Person person;

    public CommunityAdminPanel() {
        initComponents();
        populateZipcodeCBox(zipcodeComboBox);

        if (person != null && !person.getRole().equals(Role.SYSTEM_ADMIN)) {

            String city = person.getCommunity().getCity();

            textField_City.setText(city);
            textField_City.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpanel2 = new javax.swing.JTabbedPane();
        hospitalpanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblZipcode = new javax.swing.JLabel();
        textField_Address = new javax.swing.JTextField();
        textField_HospitalName = new javax.swing.JTextField();
        lblHospitalName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        textField_City = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        zipcodeComboBox = new javax.swing.JComboBox<>();
        btnAddHospital = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblHospitalRegistration = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblCommunityAdminRegistration = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblFirstname = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        textField_Firstname = new javax.swing.JTextField();
        textField_Lastname = new javax.swing.JTextField();
        textField_Contact = new javax.swing.JTextField();
        textField_Username = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        comboBox_HospitalName = new javax.swing.JComboBox<>();
        lblHospital_Name = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lbl_1Error = new javax.swing.JLabel();
        hospAdmnGenderComboBox = new javax.swing.JComboBox<>();
        textField_Password = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        lblSuccessfullyRemoved = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setName("tabpanel1"); // NOI18N

        tabpanel2.setBackground(new java.awt.Color(204, 255, 255));
        tabpanel2.setName("tabpanel2"); // NOI18N
        tabpanel2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabpanel2StateChanged(evt);
            }
        });

        hospitalpanel.setBackground(new java.awt.Color(255, 255, 255));
        hospitalpanel.setName("hospital"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblZipcode.setText("Zipcode :");

        textField_HospitalName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblHospitalName.setText("Hospital Name :");

        lblAddress.setText("Address");

        lblCity.setText("City :");

        zipcodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblZipcode, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHospitalName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_Address)
                    .addComponent(textField_HospitalName)
                    .addComponent(textField_City)
                    .addComponent(zipcodeComboBox, 0, 397, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(textField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textField_HospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHospitalName))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zipcodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblZipcode)))
                .addGap(18, 18, 18))
        );

        btnAddHospital.setBackground(new java.awt.Color(0, 153, 255));
        btnAddHospital.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHospital.setText("Add Hospital");
        btnAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        lblHospitalRegistration.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        lblHospitalRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblHospitalRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalRegistration.setText("Hospital Registration");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHospitalRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHospitalRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setText("ERROR");

        javax.swing.GroupLayout hospitalpanelLayout = new javax.swing.GroupLayout(hospitalpanel);
        hospitalpanel.setLayout(hospitalpanelLayout);
        hospitalpanelLayout.setHorizontalGroup(
            hospitalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hospitalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hospitalpanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(hospitalpanelLayout.createSequentialGroup()
                .addGroup(hospitalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hospitalpanelLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btnAddHospital))
                    .addGroup(hospitalpanelLayout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(lblError)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hospitalpanelLayout.setVerticalGroup(
            hospitalpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnAddHospital)
                .addGap(27, 27, 27)
                .addComponent(lblError)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        tabpanel2.addTab("Hospital", hospitalpanel);

        jPanel1.setName("hospital_admin_registration"); // NOI18N

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(0, 153, 255));

        lblCommunityAdminRegistration.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        lblCommunityAdminRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblCommunityAdminRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCommunityAdminRegistration.setText("Community Admin Registration");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(lblCommunityAdminRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCommunityAdminRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        lblFirstname.setText("Firstname:");

        lblLastname.setText("Lastname:");

        textField_Firstname.setText("jTextField14");

        textField_Lastname.setText("jTextField15");
        textField_Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_LastnameActionPerformed(evt);
            }
        });

        textField_Contact.setText("jTextField17");
        textField_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_ContactActionPerformed(evt);
            }
        });

        textField_Username.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
            public void removeUpdate(DocumentEvent e) {
                warn();
            }
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                for (Credentials creds : CredentialsDirectory.getCredentials()) {

                    if (textField_Username.getText().equals(creds.getUsername())) {

                        JOptionPane.showMessageDialog(null,
                            "Error: username already exists, choose a different username", "Error Message",
                            JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
        textField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_UsernameActionPerformed(evt);
            }
        });

        lblGender.setText("Gender:");

        lblContact.setText("Contact:");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        comboBox_HospitalName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblHospital_Name.setText("Hospital Name:");

        btnAdd.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.accentColor"));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.accentColor"));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lbl_1Error.setForeground(new java.awt.Color(255, 51, 51));
        lbl_1Error.setText("ERROR");

        hospAdmnGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_PasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFirstname)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGender)
                                    .addComponent(lblLastname)
                                    .addComponent(lblContact)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassword)
                                    .addComponent(lblUsername)
                                    .addComponent(lblHospital_Name))
                                .addGap(1, 1, 1)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(textField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textField_Firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(textField_Lastname)
                                .addComponent(textField_Contact, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textField_Username)
                                .addComponent(comboBox_HospitalName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hospAdmnGenderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnAdd)
                        .addGap(62, 62, 62)
                        .addComponent(btnUpdate))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(lbl_1Error)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstname)
                            .addComponent(textField_Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textField_Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender)
                            .addComponent(hospAdmnGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContact)
                            .addComponent(textField_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospital_Name)
                    .addComponent(comboBox_HospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addComponent(lbl_1Error)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabpanel2.addTab("Hospital Admin Registration", jPanel1);

        jPanel6.setName("hospitals"); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Admin", "City", "Zipcode"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnRemove.setBackground(new java.awt.Color(0, 153, 255));
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        lblSuccessfullyRemoved.setForeground(new java.awt.Color(0, 204, 51));
        lblSuccessfullyRemoved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuccessfullyRemoved.setText("Successfully Removed");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(btnRemove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSuccessfullyRemoved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(btnRemove)
                .addGap(31, 31, 31)
                .addComponent(lblSuccessfullyRemoved)
                .addGap(0, 208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabpanel2.addTab("Hospitals", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (!textField_Username.getText().equals("") && !new String(textField_Password.getPassword()).equals("")
                && !textField_Firstname.getText().equals("")
                && !hospAdmnGenderComboBox.getSelectedItem().equals("")
                && !textField_Contact.getText().equals("") && !comboBox_HospitalName.getSelectedItem().equals("")) {

            String username = textField_Username.getText();
            String password = new String(textField_Password.getPassword());

            Credentials credentials = new Credentials(username, password);

            String hospName = (String) comboBox_HospitalName.getSelectedItem();

            BBHospital hospital = null;
            Community community = null;

            for (BBHospital hosp : HospitalDirectory.getHospitals()) {

                if (hosp.getHospitalDetails().getHospitalName().equalsIgnoreCase(hospName)) {

                    hospital = hosp;
                    community = hospital.getCommunity();
                }
            }

            String firstName = textField_Firstname.getText();
            String lastName = textField_Lastname.getText();
            String phone = textField_Contact.getText();
            String gender = (String) hospAdmnGenderComboBox.getSelectedItem();

            PersonalDetails details = new PersonalDetails(firstName, lastName, gender, phone, "");

            Person hospAdmin = new Person(details, credentials, community, Role.HOSPITAL_ADMIN);
            hospital.setHospitalAdmin(hospAdmin);

            CredentialsDirectory.getCredentials().add(credentials);

            lblError.setVisible(true);
            lblError.setText("Successfully added admin: " + username);

        } else {

            lblError.setVisible(true);
            lblError.setText("Null values not allowed");
        }

        clearTextfields();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalActionPerformed
        // TODO add your handling code here:
        if (!textField_Address.getText().equals("") && !textField_HospitalName.getText().equals("")
                && !textField_City.getText().equals("") && !zipcodeComboBox.getSelectedItem().equals("")) {

            Integer zipcode = Integer.parseInt((String) zipcodeComboBox.getSelectedItem());
            String city = textField_City.getText();
            String address = textField_Address.getText();
            String hospitalName = textField_HospitalName.getText();
            BBHospital hospitals = null;
            Community foundCommunity = null;
            HospitalDetails hospDetails = null;
            ArrayList<BloodGroupDetails> bloodGroupDetails = null;

            for (Community community : CommunityDirectory.getCommunities()) {

                if (city.equals(community.getCity()) && zipcode.equals(community.getZipcode())) {

                    foundCommunity = community;

                    bloodGroupDetails = new ArrayList<>();
                    bloodGroupDetails.add(new BloodGroupDetails("A+", 0));
                    bloodGroupDetails.add(new BloodGroupDetails("A-", 0));
                    bloodGroupDetails.add(new BloodGroupDetails("B+", 0));
                    bloodGroupDetails.add(new BloodGroupDetails("B-", 0));
                    bloodGroupDetails.add(new BloodGroupDetails("O+", 0));
                    bloodGroupDetails.add(new BloodGroupDetails("O-", 0));
                    bloodGroupDetails.add(new BloodGroupDetails("AB+", 0));
                    bloodGroupDetails.add(new BloodGroupDetails("AB-", 0));

                    hospDetails = new HospitalDetails(address, hospitalName);
                    hospitals = new BBHospital(foundCommunity, bloodGroupDetails, hospDetails);
                }
            }

            if (hospitals == null) {

                lblError.setText("No such community present");
                lblError.setVisible(true);
            } else {

                HospitalDirectory.getHospitals().add(hospitals);
                foundCommunity.getHospitals().add(hospitals);

                lblError.setText("Hospital " + hospitalName + " successfully added");
                lblError.setVisible(true);
            }

        } else {
            lblError.setText("Null values not allowed");
            lblError.setVisible(true);
        }

        clearTextfields();

    }//GEN-LAST:event_btnAddHospitalActionPerformed

    private void textField_LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_LastnameActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        String hospitalName = "";

        if (selectedRow != -1) {

            BBHospital hospital = (BBHospital) hospitalResultSet.get(selectedRow);
            Community community = hospital.getCommunity();

            community.getHospitals().remove(hospital);
            HospitalDirectory.getHospitals().remove(hospital);

            removeAllRows(table);
            populateHospitalTable();

            lblSuccessfullyRemoved.setVisible(true);
            lblSuccessfullyRemoved.setText("Hospital " + hospitalName + " Removed");
        } else {

            lblSuccessfullyRemoved.setVisible(true);
            lblSuccessfullyRemoved.setText("You need to select a row!");

        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tabpanel2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabpanel2StateChanged
        // TODO add your handling code here:
        System.out.println(tabpanel2.getSelectedComponent().getName());
        if (tabpanel2.getSelectedComponent().getName().equals("Hospital")) {

            populateZipcodeCBox(zipcodeComboBox);

            lblError.setText("");
            lblError.setVisible(false);
        }

        if (tabpanel2.getSelectedComponent().getName().equals("Hospital Admin")) {

            populateHospNameCBox(comboBox_HospitalName);
        }

        if (tabpanel2.getSelectedComponent().getName().equals("Hospitals")) {

            lblSuccessfullyRemoved.setText("");
            lblSuccessfullyRemoved.setVisible(false);

            removeAllRows(table);
            populateHospitalTable();
        }


    }//GEN-LAST:event_tabpanel2StateChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (!textField_Username.getText().equals("") && !new String(textField_Password.getPassword()).equals("")
                && !textField_Firstname.getText().equals("")
                && !hospAdmnGenderComboBox.getSelectedItem().equals("")
                && !textField_Contact.getText().equals("") && !comboBox_HospitalName.getSelectedItem().equals("")) {

            String hospitalName = (String) comboBox_HospitalName.getSelectedItem();

            BBHospital hospital = null;
            Community community = null;

            for (BBHospital hosp : HospitalDirectory.getHospitals()) {

                if (hosp.getHospitalDetails().getHospitalName().equalsIgnoreCase(hospitalName)) {

                    hospital = hosp;
                    community = hospital.getCommunity();
                }
            }

            if (CredentialsDirectory.getCredentials()
                    .contains(hospital.getHospitalAdmin().getCredentials())) {

                CredentialsDirectory.getCredentials().remove(hospital.getHospitalAdmin().getCredentials());
            }

            String username = textField_Username.getText();
            String password = new String(textField_Password.getPassword());

            Credentials credentials = new Credentials(username, password);

            String firstName = textField_Firstname.getText();
            String lastName = textField_Lastname.getText();
            String phone = textField_Contact.getText();
            String gender = (String) hospAdmnGenderComboBox.getSelectedItem();

            PersonalDetails details = new PersonalDetails(firstName, lastName, gender, phone, "");

            Person hospAdmin = new Person(details, credentials, community, Role.HOSPITAL_ADMIN);
            hospital.setHospitalAdmin(hospAdmin);

            CredentialsDirectory.getCredentials().add(credentials);

            lblError.setVisible(true);
            lblError.setText("Successfully added admin: " + username);

        } else {

            lblError.setVisible(true);
            lblError.setText("Null values not allowed");
        }

        clearTextfields();


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void textField_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_ContactActionPerformed

    private void textField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_PasswordActionPerformed

    private void textField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_UsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddHospital;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboBox_HospitalName;
    private javax.swing.JComboBox<String> hospAdmnGenderComboBox;
    private javax.swing.JPanel hospitalpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunityAdminRegistration;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblHospitalRegistration;
    private javax.swing.JLabel lblHospital_Name;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSuccessfullyRemoved;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JLabel lbl_1Error;
    private javax.swing.JTabbedPane tabpanel2;
    private javax.swing.JTextField textField_Address;
    private javax.swing.JTextField textField_City;
    private javax.swing.JTextField textField_Contact;
    private javax.swing.JTextField textField_Firstname;
    private javax.swing.JTextField textField_HospitalName;
    private javax.swing.JTextField textField_Lastname;
    private javax.swing.JPasswordField textField_Password;
    private javax.swing.JTextField textField_Username;
    private javax.swing.JComboBox<String> zipcodeComboBox;
    // End of variables declaration//GEN-END:variables

    private void populateZipcodeCBox(JComboBox<String> localComboBox) {
        ArrayList<Community> communities = CommunityDirectory.getCommunities();
        ArrayList<String> zipcodes = new ArrayList<>();

        for (Community community : communities) {

            if (person.getRole().equals(Role.SYSTEM_ADMIN)) {

                zipcodes.add(Integer.toString(community.getZipcode()));
            } else {

                if (person.getCommunity().getCity().equals(community.getCity())
                        && person.getCommunity().getZipcode().equals(community.getZipcode())) {

                    zipcodes.add(Integer.toString(community.getZipcode()));
                }
            }
        }

        String[] zipArr = zipcodes.toArray(new String[zipcodes.size()]);

        DefaultComboBoxModel aModel = new DefaultComboBoxModel(zipArr);
        localComboBox.setModel(aModel);
    }

    private void populateHospNameCBox(JComboBox<String> comboBox_HospitalName) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void removeAllRows(JTable table) {

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int rowCount = model.getRowCount();
        // Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }

    private void populateHospitalTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        hospitalResultSet = new ArrayList<BBHospital>();

        for (BBHospital hospital : HospitalDirectory.getHospitals()) {

            if (person.getRole().equals(Role.SYSTEM_ADMIN)) {

                Object[] obj = new Object[4];

                obj[0] = hospital.getHospitalDetails().getHospitalName();
                obj[1] = hospital.getHospitalAdmin().getPersonalDetails().getFirstName() + " " + hospital.getHospitalAdmin().getPersonalDetails().getLastName();
                obj[2] = hospital.getCommunity().getZipcode();
                obj[3] = hospital.getCommunity().getCity();

                model.addRow(obj);
                hospitalResultSet.add(hospital);
            } else {

                String adminCity = person.getCommunity().getCity();
                Integer adminZipcode = person.getCommunity().getZipcode();

                if (adminCity.equals(hospital.getCommunity().getCity())
                        && adminZipcode.equals(hospital.getCommunity().getZipcode())) {

                    Object[] obj = new Object[4];

                    obj[0] = hospital.getHospitalDetails().getHospitalName();
                    obj[1] = hospital.getHospitalAdmin().getPersonalDetails().getFirstName() + " " + hospital.getHospitalAdmin().getPersonalDetails().getLastName();
                    obj[2] = hospital.getCommunity().getZipcode();
                    obj[3] = hospital.getCommunity().getCity();

                    model.addRow(obj);
                    hospitalResultSet.add(hospital);
                }
            }
        }
    }

    private void clearTextfields() {
        textField_Firstname.setText("");
        textField_Lastname.setText("");
        textField_Username.setText("");
        textField_Password.setText("");
        comboBox_HospitalName.setSelectedIndex(-1);
        textField_Contact.setText("");
        hospAdmnGenderComboBox.setSelectedIndex(-1);
    }
}
