/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiComponents.BloodRequestManagement;


import business.Bloodbank.directories.CommunityDirectory;
import business.Bloodbank.directories.CredentialsDirectory;
import business.Bloodbank.directories.HospitalDirectory;
import business.Bloodbank.resources.Community;
import business.Bloodbank.resources.Credentials;
import business.Bloodbank.resources.Person;
import business.Bloodbank.resources.PersonalDetails;
import business.Bloodbank.resources.Role;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class EnterpriseAdminPanel extends javax.swing.JPanel {
    
    private ArrayList<Person> communityAdminResultSet;
    private ArrayList<Community> communityResultSet;



    /**
     * Creates new form EnterpriseAdminPanel
     */
    public EnterpriseAdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblZipcode = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        zipcodeTf = new javax.swing.JTextField();
        cityTf = new javax.swing.JTextField();
        btnAddCommunity = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblCommunityRegistration = new javax.swing.JLabel();
        lblError_1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblCommunityAdminRegistration = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblFirstname = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        commAdmnFirstNameTf = new javax.swing.JTextField();
        commAdmnLastNameTf = new javax.swing.JTextField();
        commAdmnContactTf = new javax.swing.JTextField();
        commAdmnUsernameTf = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        commAdmnCityComboBox = new javax.swing.JComboBox<>();
        commAdmnZipcodeComboBox = new javax.swing.JComboBox<>();
        lblCity_1 = new javax.swing.JLabel();
        label_1 = new javax.swing.JLabel();
        btnAdd_1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        commAdmnGenderComboBox = new javax.swing.JComboBox<>();
        commAdmnPasswordTf = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lblBloodRequestAdminRegistration = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        label_2 = new javax.swing.JLabel();
        label_3 = new javax.swing.JLabel();
        bldReqAdmnFirstNameTf = new javax.swing.JTextField();
        bldReqAdmnLastNameTf = new javax.swing.JTextField();
        bldReqAdmnContactTf = new javax.swing.JTextField();
        bldReqAdmnUsernameTf = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        label_4 = new javax.swing.JLabel();
        label_5 = new javax.swing.JLabel();
        label_6 = new javax.swing.JLabel();
        bldReqAdmnCityComboBox = new javax.swing.JComboBox<>();
        bldReqAdmnZipcodeComboBox = new javax.swing.JComboBox<>();
        label_7 = new javax.swing.JLabel();
        label_8 = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        lblError_2 = new javax.swing.JLabel();
        bldReqAdmnGenderComboBox = new javax.swing.JComboBox<>();
        bldReqAdmnPasswordTf = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRemove_2 = new javax.swing.JButton();
        lblPatientsEncountersDoctors = new javax.swing.JLabel();

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create Community Admin");

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 255, 255));

        jTabbedPane3.setBackground(new java.awt.Color(204, 255, 255));
        jTabbedPane3.setName("JTabbedPane3"); // NOI18N
        jTabbedPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane3StateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName("jTabbedPane3"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblZipcode.setText("Zipcode :");

        lblCity.setText("City :");

        zipcodeTf.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }

            public void removeUpdate(DocumentEvent e) {
                warn();
            }

            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {

                for (Community comm : CommunityDirectory.getCommunities()) {

                    if (zipcodeTf.getText().equals(comm.getZipcode().toString())) {
                        JOptionPane.showMessageDialog(null, "Error: Zipcode already exists, choose another one",
                            "Error Message", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });

        cityTf.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }

            public void removeUpdate(DocumentEvent e) {
                warn();
            }

            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {

                for (Community comm : CommunityDirectory.getCommunities()) {

                    if (cityTf.getText().equals(comm.getCity())) {
                        JOptionPane.showMessageDialog(null, "Error: Zipcode already exists, choose another one",
                            "Error Message", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
        cityTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAddCommunity.setBackground(new java.awt.Color(0, 153, 255));
        btnAddCommunity.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAddCommunity.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCommunity.setText("Add Community");
        btnAddCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblZipcode)
                        .addGap(72, 72, 72))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCity)
                        .addGap(102, 102, 102)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(353, 353, 353))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(btnAddCommunity)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipcode))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblCity))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnAddCommunity)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setName("jTabbedPane3"); // NOI18N

        lblCommunityRegistration.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        lblCommunityRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblCommunityRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCommunityRegistration.setText("Community Registration");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblCommunityRegistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(lblCommunityRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        lblError_1.setForeground(new java.awt.Color(255, 0, 51));
        lblError_1.setText("ERROR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(lblError_1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblError_1)
                .addContainerGap(565, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Community", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jTabbedPane3"); // NOI18N

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(0, 153, 255));

        lblCommunityAdminRegistration.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        lblCommunityAdminRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblCommunityAdminRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCommunityAdminRegistration.setText("Community Admin Registration");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(lblCommunityAdminRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCommunityAdminRegistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        lblFirstname.setText("Firstname:");

        lblLastname.setText("Lastname:");

        commAdmnFirstNameTf.setText("jTextField14");
        commAdmnFirstNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commAdmnFirstNameTfActionPerformed(evt);
            }
        });

        commAdmnLastNameTf.setText("jTextField15");
        commAdmnLastNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commAdmnLastNameTfActionPerformed(evt);
            }
        });

        commAdmnContactTf.setText("jTextField17");
        commAdmnContactTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commAdmnContactTfActionPerformed(evt);
            }
        });

        commAdmnUsernameTf.setText("jTextField18");
        commAdmnUsernameTf.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
            public void removeUpdate(DocumentEvent e) {
                warn();
            }
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                for (Credentials creds : CredentialsDirectory.getCredentials()) {

                    if (commAdmnUsernameTf.getText().equals(creds.getUsername())) {

                        JOptionPane.showMessageDialog(null,
                            "Error: username already exists, choose a different username", "Error Message",
                            JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
        commAdmnUsernameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commAdmnUsernameTfActionPerformed(evt);
            }
        });

        lblGender.setText("Gender:");

        lblContact.setText("Contact:");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        commAdmnCityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        commAdmnZipcodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCity_1.setText("City:");

        label_1.setText("Zipcode:");

        btnAdd_1.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd_1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAdd_1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd_1.setText("Add");
        btnAdd_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_1ActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setText("ERROR");

        commAdmnGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        commAdmnPasswordTf.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(btnAdd_1)
                        .addGap(148, 148, 148)
                        .addComponent(btnUpdate))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(lblError)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_1)
                        .addGap(107, 107, 107)
                        .addComponent(commAdmnZipcodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(6, 341, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(lblFirstname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(commAdmnFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(lblLastname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(commAdmnLastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(lblGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(commAdmnGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword)
                                    .addComponent(lblCity_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(commAdmnPasswordTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(commAdmnCityComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(commAdmnContactTf)
                                    .addComponent(commAdmnUsernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(277, 277, 277))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commAdmnFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commAdmnLastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commAdmnGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commAdmnContactTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commAdmnUsernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commAdmnPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commAdmnCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commAdmnZipcodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_1))
                .addGap(34, 34, 34)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnAdd_1))
                        .addGap(37, 37, 37))
                    .addComponent(lblError, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Community Admin", jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setName("jTabbedPane3"); // NOI18N

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(0, 153, 255));

        lblBloodRequestAdminRegistration.setBackground(new java.awt.Color(255, 255, 255));
        lblBloodRequestAdminRegistration.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        lblBloodRequestAdminRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblBloodRequestAdminRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBloodRequestAdminRegistration.setText("Blood Request Admin Registration");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBloodRequestAdminRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBloodRequestAdminRegistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        label_2.setText("Firstname:");

        label_3.setText("Lastname:");

        bldReqAdmnFirstNameTf.setText("jTextField14");
        bldReqAdmnFirstNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldReqAdmnFirstNameTfActionPerformed(evt);
            }
        });

        bldReqAdmnLastNameTf.setText("jTextField15");
        bldReqAdmnLastNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldReqAdmnLastNameTfActionPerformed(evt);
            }
        });

        bldReqAdmnContactTf.setText("jTextField17");

        bldReqAdmnUsernameTf.setText("jTextField18");
        bldReqAdmnUsernameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldReqAdmnUsernameTfActionPerformed(evt);
            }
        });

        label.setText("Gender:");

        label_4.setText("Contact:");

        label_5.setText("Username:");

        label_6.setText("Password:");

        bldReqAdmnCityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bldReqAdmnCityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldReqAdmnCityComboBoxActionPerformed(evt);
            }
        });

        bldReqAdmnZipcodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_7.setText("City:");

        label_8.setText("Zipcode:");

        button.setBackground(new java.awt.Color(0, 153, 255));
        button.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Add");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        button_1.setBackground(new java.awt.Color(0, 153, 255));
        button_1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        button_1.setForeground(new java.awt.Color(255, 255, 255));
        button_1.setText("Update");
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        lblError_2.setForeground(new java.awt.Color(255, 51, 51));
        lblError_2.setText("ERROR");

        bldReqAdmnGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bldReqAdmnGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldReqAdmnGenderComboBoxActionPerformed(evt);
            }
        });

        bldReqAdmnPasswordTf.setText("jPasswordField2");
        bldReqAdmnPasswordTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldReqAdmnPasswordTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label_6)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_8)
                                    .addComponent(label_7)))
                            .addGap(133, 133, 133)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bldReqAdmnZipcodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bldReqAdmnCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bldReqAdmnPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label)
                                .addComponent(label_3)
                                .addComponent(label_4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_5))
                            .addGap(129, 129, 129)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bldReqAdmnGenderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bldReqAdmnUsernameTf)
                                .addComponent(bldReqAdmnContactTf)
                                .addComponent(bldReqAdmnLastNameTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(label_2)
                        .addGap(132, 132, 132)
                        .addComponent(bldReqAdmnFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(button)
                        .addGap(174, 174, 174)
                        .addComponent(button_1)
                        .addGap(69, 69, 69)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(lblError_2)
                .addContainerGap(548, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldReqAdmnFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldReqAdmnLastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldReqAdmnGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bldReqAdmnContactTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bldReqAdmnUsernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bldReqAdmnPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bldReqAdmnCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(label_6)
                        .addGap(18, 18, 18)
                        .addComponent(label_7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_8)
                    .addComponent(bldReqAdmnZipcodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button)
                    .addComponent(button_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblError_2)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Blood Request Admin", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setName("jTabbedPane3"); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "City", "Zipcode", "Community Admin", "Blood Request Admin"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnRemove_2.setBackground(new java.awt.Color(0, 153, 255));
        btnRemove_2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnRemove_2.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove_2.setText("Remove");
        btnRemove_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove_2ActionPerformed(evt);
            }
        });

        lblPatientsEncountersDoctors.setForeground(new java.awt.Color(0, 204, 51));
        lblPatientsEncountersDoctors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientsEncountersDoctors.setText("Successfully Removed");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemove_2)
                .addContainerGap())
            .addComponent(lblPatientsEncountersDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemove_2)
                .addGap(59, 59, 59)
                .addComponent(lblPatientsEncountersDoctors)
                .addGap(0, 607, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Communities", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnAdd_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_1ActionPerformed
        // TODO add your handling code here:
        if (!commAdmnUsernameTf.getText().equals("") && !new String(commAdmnPasswordTf.getPassword()).equals("")
						&& !commAdmnFirstNameTf.getText().equals("")
						&& !commAdmnGenderComboBox.getSelectedItem().equals("")
						&& !commAdmnContactTf.getText().equals("")
						&& !commAdmnZipcodeComboBox.getSelectedItem().equals("")
						&& !commAdmnCityComboBox.getSelectedItem().equals("")) {

					String username = commAdmnUsernameTf.getText();
					String password = new String(commAdmnPasswordTf.getPassword());

					Credentials credentials = new Credentials(username, password);

					String city = (String) commAdmnCityComboBox.getSelectedItem();
					Integer zipcode = Integer.valueOf((String) commAdmnZipcodeComboBox.getSelectedItem());
					Community community = null;

					for (Community comm : CommunityDirectory.getCommunities()) {

						if (city.equals(comm.getCity()) && zipcode.equals(comm.getZipcode())) {

							community = comm;
						}
					}

					String firstName = commAdmnFirstNameTf.getText();
					String lastName = commAdmnLastNameTf.getText();
					String phone = commAdmnContactTf.getText();
					String gender = (String) commAdmnGenderComboBox.getSelectedItem();

					PersonalDetails details = new PersonalDetails(firstName, lastName, gender, phone, "");

					Person commAdmin = new Person(details, credentials, community, Role.COMMUNITY_ADMIN);
					community.setCommunityAdmin(commAdmin);

					CredentialsDirectory.getCredentials().add(credentials);

					lblError_1.setVisible(true);
					lblError_1.setText("Successfully added admin: " + username);

				} else {

					lblError_1.setVisible(true);
					lblError_1.setText("Null values not allowed");
				}

				clearTextfields();
    }//GEN-LAST:event_btnAdd_1ActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        if (!bldReqAdmnContactTf.getText().equals("") && !new String(bldReqAdmnPasswordTf.getPassword()).equals("")
						&& !bldReqAdmnFirstNameTf.getText().equals("")
						&& !bldReqAdmnGenderComboBox.getSelectedItem().equals("")
						&& !bldReqAdmnContactTf.getText().equals("")
						&& !bldReqAdmnZipcodeComboBox.getSelectedItem().equals("")
						&& !bldReqAdmnCityComboBox.getSelectedItem().equals("")) {

					String username = bldReqAdmnContactTf.getText();
					String password = new String(bldReqAdmnPasswordTf.getPassword());

					Credentials credentials = new Credentials(username, password);

					String city = (String) bldReqAdmnCityComboBox.getSelectedItem();
					Integer zipcode = Integer.parseInt((String) bldReqAdmnZipcodeComboBox.getSelectedItem());
					Community community = null;

					for (Community comm : CommunityDirectory.getCommunities()) {

						if (city.equals(comm.getCity()) && zipcode.equals(comm.getZipcode())) {

							community = comm;
						}
					}
					
					String firstName 	= bldReqAdmnFirstNameTf.getText();
					String lastName 	= bldReqAdmnLastNameTf.getText();
					String phone 		= bldReqAdmnContactTf.getText();
					String gender 		= (String) bldReqAdmnGenderComboBox.getSelectedItem();

					PersonalDetails details = new PersonalDetails(firstName, lastName, gender, phone, "");

					Person bldReqAdmin = new Person(details, credentials, community, Role.BLOODREQUEST_ADMIN);
					community.setBloodReqAdmin(bldReqAdmin);

					CredentialsDirectory.getCredentials().add(credentials);

					lblError_1.setVisible(true);
					lblError_1.setText("Successfully added admin: " + username);

				} else {

					lblError_1.setVisible(true);
					lblError_1.setText("Null values not allowed");
				}

				clearTextfields();
    }//GEN-LAST:event_buttonActionPerformed

    private void btnRemove_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove_2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

				if (selectedRow != -1) {

					Community community = communityResultSet.get(selectedRow);
					HospitalDirectory.getHospitals().remove(community.getHospitals());
					community.setCommunityAdmin(null);
					community.setBloodReqAdmin(null);
					
					
					// Dont remove the community, however remove all data of the community
					// since houses and people data would stay relate to communities
					// CommunityDirectory.getCommunities().remove( selectedRow );
					removeAllRows(jTable1);
					populateCommunityTable();
					// populateCommunityAdminTable(community);

					lblPatientsEncountersDoctors.setVisible(true);
					lblPatientsEncountersDoctors.setText("Patients, Encounters, Doctors & Hospitals Removed");
				} else {

					lblPatientsEncountersDoctors.setVisible(true);
                                }				lblPatientsEncountersDoctors.setText("You need to select a row!");
    }//GEN-LAST:event_btnRemove_2ActionPerformed

    private void jTabbedPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane3StateChanged
        // TODO add your handling code here:
        if (jTabbedPane3.getSelectedComponent().getName().equals("Community")) {

					lblError_1.setVisible(false);
					lblError_1.setText("");
				}

				if (jTabbedPane3.getSelectedComponent().getName().equals("Community Admin")) {
					
					populateZipcodeCBox(commAdmnZipcodeComboBox);
					populateCityCBox(commAdmnCityComboBox);
					
					lblError_1.setVisible(false);
					lblError_1.setText("");
				}
				
				if (jTabbedPane3.getSelectedComponent().getName().equals("Blood Request Admin")) {
					
					populateZipcodeCBox(bldReqAdmnZipcodeComboBox);
					populateCityCBox(bldReqAdmnCityComboBox);
					
					lblError_1.setVisible(false);
					lblError_1.setText("");
				}

				if (jTabbedPane3.getSelectedComponent().getName().equals("Communities")) {

					lblPatientsEncountersDoctors.setVisible(false);
					lblPatientsEncountersDoctors.setText("");
					
					removeAllRows(jTable1);
					populateCommunityTable();
				}
                                

    }//GEN-LAST:event_jTabbedPane3StateChanged

    private void btnAddCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommunityActionPerformed
        // TODO add your handling code here:
        if (!zipcodeTf.getText().equals("") && !cityTf.getText().equals("")) {

					Integer zipcode = Integer.parseInt(zipcodeTf.getText());
					String city = cityTf.getText();
					Community community = new Community(zipcode, city);

					CommunityDirectory.getCommunities().add(community);

					lblError_1.setVisible(true);
					lblError_1.setText("Added Community: " + " | " + "Zipcode:" + zipcode + " | " + "City: " + city);

				} else {

					lblError_1.setVisible(true);
					lblError_1.setText("Null values not allowed");
				}

				clearTextfields();
    }//GEN-LAST:event_btnAddCommunityActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (!commAdmnUsernameTf.getText().equals("") && !new String(commAdmnPasswordTf.getPassword()).equals("")
						&& !commAdmnFirstNameTf.getText().equals("")
						&& !commAdmnGenderComboBox.getSelectedItem().equals("")
						&& !commAdmnContactTf.getText().equals("")
						&& !commAdmnZipcodeComboBox.getSelectedItem().equals("")
						&& !commAdmnCityComboBox.getSelectedItem().equals("")) {
					
					String city = (String) commAdmnCityComboBox.getSelectedItem();
					Integer zipcode = Integer.parseInt((String) commAdmnZipcodeComboBox.getSelectedItem());
					Community community = null;

					for (Community comm : CommunityDirectory.getCommunities()) {

						if (city.equals(comm.getCity()) && zipcode.equals(comm.getZipcode())) {

							community = comm;
						}
					}
					
					if(CredentialsDirectory.getCredentials().contains(community.getCommunityAdmin().getCredentials())) {
						
						CredentialsDirectory.getCredentials().remove(community.getCommunityAdmin().getCredentials());
					}
					
					String username = commAdmnUsernameTf.getText();
					String password = new String(commAdmnPasswordTf.getPassword());

					Credentials credentials = new Credentials(username, password);
					
					String firstName = commAdmnFirstNameTf.getText();
					String lastName = commAdmnLastNameTf.getText();
					String phone = commAdmnContactTf.getText();
					String gender = (String) commAdmnGenderComboBox.getSelectedItem();

					PersonalDetails details = new PersonalDetails(firstName, lastName, gender, phone, "");

					Person commAdmin = new Person(details, credentials, community, Role.COMMUNITY_ADMIN);
					community.setCommunityAdmin(commAdmin);

					CredentialsDirectory.getCredentials().add(credentials);

					lblError_1.setVisible(true);
					lblError_1.setText("Successfully added admin: " + username);

				} else {

					lblError_1.setVisible(true);
					lblError_1.setText("Null values not allowed");
				}

				clearTextfields();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        // TODO add your handling code here:
        
				if (!bldReqAdmnContactTf.getText().equals("") && !new String(bldReqAdmnPasswordTf.getPassword()).equals("")
						&& !bldReqAdmnFirstNameTf.getText().equals("")
						&& !bldReqAdmnGenderComboBox.getSelectedItem().equals("")
						&& !bldReqAdmnContactTf.getText().equals("")
						&& !bldReqAdmnZipcodeComboBox.getSelectedItem().equals("")
						&& !bldReqAdmnCityComboBox.getSelectedItem().equals("")) {
					
					String city = (String) bldReqAdmnCityComboBox.getSelectedItem();
					Integer zipcode = Integer.parseInt((String) bldReqAdmnZipcodeComboBox.getSelectedItem());
					Community community = null;

					for (Community comm : CommunityDirectory.getCommunities()) {

						if (city.equals(comm.getCity()) && zipcode.equals(comm.getZipcode())) {

							community = comm;
						}
					}
					
					if(CredentialsDirectory.getCredentials().contains(community.getCommunityAdmin().getCredentials())) {
						
						CredentialsDirectory.getCredentials().remove(community.getCommunityAdmin().getCredentials());
					}
					
					String username = bldReqAdmnContactTf.getText();
					String password = new String(bldReqAdmnPasswordTf.getPassword());

					Credentials credentials = new Credentials(username, password);
					
					String firstName = bldReqAdmnFirstNameTf.getText();
					String lastName = bldReqAdmnLastNameTf.getText();
					String phone = bldReqAdmnContactTf.getText();
					String gender = (String) bldReqAdmnGenderComboBox.getSelectedItem();

					PersonalDetails details = new PersonalDetails(firstName, lastName, gender, phone, "");

					Person bldReqAdmin = new Person(details, credentials, community, Role.BLOODREQUEST_ADMIN);
					community.setBloodReqAdmin(bldReqAdmin);

					CredentialsDirectory.getCredentials().add(credentials);

					lblError_1.setVisible(true);
					lblError_1.setText("Successfully added admin: " + username);

				} else {

					lblError_1.setVisible(true);
					lblError_1.setText("Null values not allowed");
				}

				clearTextfields();
    }//GEN-LAST:event_button_1ActionPerformed

    private void commAdmnContactTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commAdmnContactTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commAdmnContactTfActionPerformed

    private void commAdmnUsernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commAdmnUsernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commAdmnUsernameTfActionPerformed

    private void bldReqAdmnFirstNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldReqAdmnFirstNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldReqAdmnFirstNameTfActionPerformed

    private void commAdmnLastNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commAdmnLastNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commAdmnLastNameTfActionPerformed

    private void commAdmnFirstNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commAdmnFirstNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commAdmnFirstNameTfActionPerformed

    private void bldReqAdmnPasswordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldReqAdmnPasswordTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldReqAdmnPasswordTfActionPerformed

    private void bldReqAdmnUsernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldReqAdmnUsernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldReqAdmnUsernameTfActionPerformed

    private void bldReqAdmnGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldReqAdmnGenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldReqAdmnGenderComboBoxActionPerformed

    private void bldReqAdmnLastNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldReqAdmnLastNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldReqAdmnLastNameTfActionPerformed

    private void bldReqAdmnCityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldReqAdmnCityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldReqAdmnCityComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bldReqAdmnCityComboBox;
    private javax.swing.JTextField bldReqAdmnContactTf;
    private javax.swing.JTextField bldReqAdmnFirstNameTf;
    private javax.swing.JComboBox<String> bldReqAdmnGenderComboBox;
    private javax.swing.JTextField bldReqAdmnLastNameTf;
    private javax.swing.JPasswordField bldReqAdmnPasswordTf;
    private javax.swing.JTextField bldReqAdmnUsernameTf;
    private javax.swing.JComboBox<String> bldReqAdmnZipcodeComboBox;
    private javax.swing.JButton btnAddCommunity;
    private javax.swing.JButton btnAdd_1;
    private javax.swing.JButton btnRemove_2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton button;
    private javax.swing.JButton button_1;
    private javax.swing.JTextField cityTf;
    private javax.swing.JComboBox<String> commAdmnCityComboBox;
    private javax.swing.JTextField commAdmnContactTf;
    private javax.swing.JTextField commAdmnFirstNameTf;
    private javax.swing.JComboBox<String> commAdmnGenderComboBox;
    private javax.swing.JTextField commAdmnLastNameTf;
    private javax.swing.JPasswordField commAdmnPasswordTf;
    private javax.swing.JTextField commAdmnUsernameTf;
    private javax.swing.JComboBox<String> commAdmnZipcodeComboBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label_1;
    private javax.swing.JLabel label_2;
    private javax.swing.JLabel label_3;
    private javax.swing.JLabel label_4;
    private javax.swing.JLabel label_5;
    private javax.swing.JLabel label_6;
    private javax.swing.JLabel label_7;
    private javax.swing.JLabel label_8;
    private javax.swing.JLabel lblBloodRequestAdminRegistration;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity_1;
    private javax.swing.JLabel lblCommunityAdminRegistration;
    private javax.swing.JLabel lblCommunityRegistration;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblError_1;
    private javax.swing.JLabel lblError_2;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPatientsEncountersDoctors;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JTextField zipcodeTf;
    // End of variables declaration//GEN-END:variables

    private void clearTextfields() {
        	commAdmnFirstNameTf.setText(" ");
		commAdmnLastNameTf.setText(" ");
		commAdmnUsernameTf.setText(" ");
		commAdmnPasswordTf.setText(" ");
		commAdmnGenderComboBox.setSelectedIndex(-1);
		commAdmnContactTf.setText(" ");
		commAdmnZipcodeComboBox.setSelectedIndex(-1);
		commAdmnCityComboBox.setSelectedIndex(-1);
		
		bldReqAdmnFirstNameTf.setText(" ");
		bldReqAdmnLastNameTf.setText(" ");
		bldReqAdmnContactTf.setText(" ");
		bldReqAdmnPasswordTf.setText(" ");
		bldReqAdmnGenderComboBox.setSelectedIndex(-1);
		bldReqAdmnContactTf.setText(" ");
		bldReqAdmnZipcodeComboBox.setSelectedIndex(-1);
		bldReqAdmnCityComboBox.setSelectedIndex(-1);
	}



    private void populateCommunityTable() {
    	DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		communityResultSet = new ArrayList<Community>();

		for (Community community : CommunityDirectory.getCommunities()) {

			Object[] obj = new Object[4];

			obj[0] = community.getCity();
			obj[1] = community.getZipcode();
			obj[2] = community.getCommunityAdmin();
			obj[3] = community.getBloodReqAdmin();

			model.addRow(obj);
			communityResultSet.add(community);
		}
    }

   	private void removeAllRows(JTable table) {

		DefaultTableModel model = (DefaultTableModel) table.getModel();
		int rowCount = model.getRowCount();
		// Remove rows one by one from the end of the table
		for (int i = rowCount - 1; i >= 0; i--) {
			model.removeRow(i);
		}
	}

   
    private void populateZipcodeCBox(JComboBox<String> localComboBox) {

		ArrayList<Community> communities = CommunityDirectory.getCommunities();
		ArrayList<Integer> zipcodes = new ArrayList<Integer>();

		for (Community community : communities) {

			zipcodes.add(community.getZipcode());
		}

		Integer[] zipArr = zipcodes.toArray(new Integer[zipcodes.size()]);

		DefaultComboBoxModel aModel = new DefaultComboBoxModel(zipArr);
		localComboBox.setModel(aModel);
	}

	private void populateCityCBox(JComboBox<String> localComboBox) {

		ArrayList<Community> communities = CommunityDirectory.getCommunities();
		ArrayList<String> cities = new ArrayList<String>();

		for (Community community : communities) {

			cities.add(community.getCity());
		}

		Integer[] cityArr = cities.toArray(new Integer[cities.size()]);

		DefaultComboBoxModel aModel = new DefaultComboBoxModel(cityArr);
		localComboBox.setModel(aModel);
        }
}
